test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,15 +1,40 @@
-name: CI
+# name: CI
+# on: [push]
+# jobs:
+#     lighthouseci:
+#         runs-on: ubuntu-latest
+#         steps:
+#             - uses: actions/checkout@v2
+#             - uses: actions/setup-node@v1
+#             - run: npm install && npm install -g @lhci/cli@0.6.x
+#             - run: npm run build
+#             - run: lhci autorun
+#               env:
+#                   LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+
+#                   # 
+
+
+
+name: Ironman challenge lighthouse-ci demo
 on: [push]
 jobs:
-    lighthouseci:
-        runs-on: ubuntu-latest
-        steps:
-            - uses: actions/checkout@v2
-            - uses: actions/setup-node@v1
-            - run: npm install && npm install -g @lhci/cli@0.6.x
-            - run: npm run build
-            - run: lhci autorun
-              env:
-                  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
-
-                  #
+  lhci:
+    name: Lighthouse CI
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v1
+      - name: Use Node.js
+        uses: actions/setup-node@v1
+        with:
+          node-version: 12.x
+      - name: npm install, build
+        run: |
+          yarn
+          npm run build
+      - name: run lighthouse-ci
+        run: |
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+        env:
+          LHCI_GITHUB_APP_TOKEN: ZrmCcLXdS9x0:27504719:GdZ1BunOpGEM
